name: harmony-docker

on:
  workflow_dispatch:
    inputs:
      version:
        description: "release version/tag"
        required: true

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-22.04

    steps:
      - name: Cache OpenHarmony SDK
        id: cache-sdk
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/siyuan-note/ohos-sdk/
          key: ${{ runner.os }}-openharmony-sdk-5.1.0.54-20250313_021647
          restore-keys: |
            ${{ runner.os }}-openharmony-sdk-
      - name: Create ohos-sdk directory
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ github.workspace }}/siyuan-note/ohos-sdk/
        shell: bash

      - name: Download OpenHarmony SDK
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/siyuan-note/ohos-sdk/
        run: |
          # 下载 OpenHarmony SDK
          wget https://cidownload.openharmony.cn/version/Master_Version/OpenHarmony_5.1.0.54/20250313_021647/version-Master_Version-OpenHarmony_5.1.0.54-20250313_021647-ohos-sdk-public.tar.gz
          tar -xzvf *.tar.gz
          ls -lh
      

      - name: unzip ohos-sdk
        working-directory: ${{ github.workspace }}/siyuan-note/ohos-sdk/
        run: |
          ls -lh
          cd version-Master_Version-OpenHarmony_5.1.0.54-20250313_021647-ohos-sdk-public/linux && for i in *.zip;do unzip $i;done && rm *.zip 
          cd ..
          tar -cvf ${{ github.workspace }}/siyuan-note/ohos-sdk/linux.tar linux
        shell: bash

      - uses: joutvhu/get-release@v1
        id: get_current_release
        with:
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ohos-sdk
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_current_release.outputs.upload_url }}
          asset_name: ohos-linux1.tar
          asset_path: ${{ github.workspace }}/siyuan-note/ohos-sdk/linux.tar
          asset_content_type: application/octet-stream