name: release-assets

on:
  workflow_dispatch:
    inputs:
      version:
        description: "release version/tag"
        required: true
      packageManager:
        description: "pnpm@x.x.x"
        required: true

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-22.04
#            kernel_path: "../../../siyuan-android/app/libs/kernel.aar"

    steps:
      - uses: actions/checkout@v4
        with:
          path: siyuan-note

      - name: clone origin and apply patches
        run: |
          mkdir -p ${{ github.workspace }}/go
          cd ${{ github.workspace }}/siyuan-note/

          git clone --branch ${{ github.event.inputs.version }} --depth=1 https://github.com/siyuan-note/siyuan.git
          cd siyuan

          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan/disable-update.patch
          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan/default-config.patch
          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan/mock-vip-user.patch

          git status
          
          cd ..
               
          mkdir -p /mnt/f/
               
          git clone --branch main --depth=1 https://github.com/harmony-contrib/log-adaptor.git /mnt/f/
          wget https://github.com/mhlywxl/siyuan-patch/releases/download/v3.1.32/ohos-linux.tar
          tar -xvf ohos-linux.tar -C /mnt/f/
          rm -rf ohos-linux.tar
          
          git clone --branch ${{ github.event.inputs.version }} --depth=1 https://github.com/siyuan-note/siyuan-harmony.git
          cd siyuan-harmony

#          git apply ${{ github.workspace }}/siyuan-note/patches/siyuan-harmony/debug-build.patch

          mkdir -p entry/libs/
          cp -r /mnt/f/log-adaptor/dist/. entry/libs/
          mkdir -p entry/src/main/resources/rawfile/

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ github.workspace }}/siyuan-note/siyuan/kernel/go.mod
          cache-dependency-path: "**/*.sum"
      - run: |
          go version
          whereis go
          cd ${{ github.workspace }}/siyuan-note/siyuan/kernel/harmony
          ./build.sh && mv libkernel.so 
          

#      - name: Set up Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#
#      - name: Install Node pnpm
#        run: npm install -g ${{ github.event.inputs.packageManager }}
#        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/app
#
#      - name: Install Node Dependencies
#        run: pnpm install --no-frozen-lockfile
#        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/app
#
#      - name: Building UI
#        run: pnpm run build
#        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/app
#
#      - name: android assets
#        working-directory: ${{ github.workspace }}/siyuan-note/siyuan/app/
#        run: |
#          zip -r ${{ github.workspace }}/siyuan-note/app.zip ./appearance ./guide ./stage ./changelogs
#
#      - uses: joutvhu/get-release@v1
#        id: get_current_release
#        with:
#          tag_name: ${{ github.event.inputs.version }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Upload assets
#        uses: shogo82148/actions-upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.get_current_release.outputs.upload_url }}
#          asset_name: siyuan-${{ github.event.inputs.version }}-app.zip
#          asset_path: ${{ github.workspace }}/siyuan-note/app.zip
#          asset_content_type: application/octet-stream
